

TOOL_CONFFILE_NAME = '.mbed-vscode-tools.json'
TOOL_CONFFILE_INDENT_LENGTH = 4
CMAKE_ROOTDIR_NAME = 'cmake_build'
CMAKE_CONFFILE_NAME = 'mbed_config.cmake'
NINJA_BUILDFILE_NAME = 'build.ninja'
VSCODE_CONFFILE_NAME = 'c_cpp_properties.json'
VSCODE_CONFFILE_INDENT_LENGTH = 4
VSCODE_CONFENTRY_BASE = 'MbedBase'
VSCODE_CONFENTRY_AUTO = 'MbedAuto'
